// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// heatindex_vec
Rcpp::NumericVector heatindex_vec(Rcpp::NumericVector Ta, Rcpp::NumericVector RH);
RcppExport SEXP _heatindex_heatindex_vec(SEXP TaSEXP, SEXP RHSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Ta(TaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type RH(RHSEXP);
    rcpp_result_gen = Rcpp::wrap(heatindex_vec(Ta, RH));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_heatindex_heatindex_vec", (DL_FUNC) &_heatindex_heatindex_vec, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_heatindex(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
