# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

heatindex_vec <- function(Ta, RH) {
    .Call(`_heatindex_heatindex_vec`, Ta, RH)
}

